<a href="https://colab.research.google.com/github/shrabanshah/18cse193_assignment_2Numy.ipynb/blob/main/18cse193_assignment_2Numy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
arr=[int(i) for i in input().split()]
arr=np.array(arr)
arr

1 2 3 4 5


array([1, 2, 3, 4, 5])

In [5]:
print(np.__version__)

1.18.5


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
#tuple to create array
arr=np.array((4,5,6,7,8,9))
arr

array([4, 5, 6, 7, 8, 9])

In [8]:
#create a 0-D array
a=np.array(20)
a

array(20)

In [9]:
#create a 1-D array
a=np.array([4,5,6,7,8,9])
a

array([4, 5, 6, 7, 8, 9])

In [10]:
#create a 2-D array
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
#create a 3-D array
arr= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('print 3 rd element of 1stdim', arr[0, 3])

print 3 rd element of 1stdim 4


In [13]:
#check number of dimensions
a=np.array(10)
b=np.array([1,2,3,4,5])
c=np.array([[1, 2, 3], [4, 5, 6]])
d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [16]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [17]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [18]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
